services:
  frontend:
    image: swczk/spray-frontend:latest
    container_name: spray-frontend
    ports:
      - "80:80"
    depends_on:
      - spring-api
      - graphql-api
    networks:
      - spray-network
    restart: always

  spring-api:
    image: swczk/spray-spring-api:latest
    container_name: spray-spring-api
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: ${DATABASE_URL:?DATABASE_URL is required}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:?POSTGRES_USER is required}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION:?AWS_COGNITO_REGION is required}
      AWS_COGNITO_URL: ${AWS_COGNITO_URL:?AWS_COGNITO_URL is required}
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID:?AWS_COGNITO_USER_POOL_ID is required}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID:?AWS_COGNITO_CLIENT_ID is required}
      AWS_COGNITO_CLIENT_SECRET: ${AWS_COGNITO_CLIENT_SECRET:?AWS_COGNITO_CLIENT_SECRET is required}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-admin}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin123}
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - spray-network
    restart: always

  graphql-api:
    image: swczk/spray-graphql-api:latest
    container_name: spray-graphql-api
    environment:
      MONGO_URI: ${MONGO_URI:?MONGO_URI is required}
      MONGO_DATABASE: ${MONGO_DATABASE:?MONGO_DATABASE is required}
      PORT: 8080
    networks:
      - spray-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: spray-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin123}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - spray-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  message-consumer:
    image: swczk/spray-message-consumer:latest
    container_name: spray-message-consumer
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-admin}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-admin123}
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    networks:
      - spray-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  spray-network:
    driver: bridge

volumes:
  rabbitmq_data:
